### ISSUE TITLE
Set `z-index` of FloatingOverlay contextmenu to maximum possible

### ISSUE THREAD

**Issue by atomiks** [ericclemmons/click-to-component#24]
Cool lib, discovered it's using Floating UI 😄 

**Describe the bug**
Right now if the webpage has positioned elements, the context menu can be obscured beneath them.

<img width="583" alt="Screen Shot 2022-04-27 at 8 58 39 am" src="https://user-images.githubusercontent.com/22450188/165406285-3063b654-cef2-456f-a72d-77a518837678.png">

It may be a good idea to set the `z-index` of the FloatingOverlay to `2147483647` to ensure it's always above everything else. (In fact, `FloatingOverlay` maybe should do that by default?)

**To Reproduce**
Right click

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser Chrome
 - Version 100

**Additional context**

**Comment by ferezoz** [comment]
Cool library @ericclemmons! I am giving a +1 for this as I am getting the context menu below modals or any element which has a z-index more than 0

**Comment by ericclemmons** [comment]
Fixed via #36 !
