### ISSUE TITLE
Error when runs from WSL

### ISSUE THREAD

**Issue by equiman** [ericclemmons/click-to-component#27]
Paths are not working with WSL.

**To Reproduce**
1. Create a project with Vite inside WSL
2. Opened it on VS Code using the [Remote - WSL](https://marketplace.visualstudio.com/items?itemName=ms-vscode-remote.remote-wsl) extension.
3. Install `click-to-component` and add the configs
4. Run de project
5. Click on the secondary button and show the context menu with components
  ![image](https://user-images.githubusercontent.com/933393/165579687-57c88a6c-c6d4-43f1-9f34-f85ca3fad91c.png)
6. Click on <App> component
7. Show an error on VSCode
  ![image](https://user-images.githubusercontent.com/933393/165578851-235b0f35-c9bf-4682-b82d-f616d087bc14.png)
8. If click on [Yes] button, show this message
  ![image](https://user-images.githubusercontent.com/933393/165580443-14edda0b-7796-4f85-944b-eccf1f0f4be4.png)
9. This is the message that shows the console in Chrome
  ![image](https://user-images.githubusercontent.com/933393/165581690-2ca8a1e8-cdb1-4d34-9f68-fabec6362334.png)

**Expected behavior**
Open in VSCode without error

**Desktop:**
 - OS: Windows 10 21H2
 - Browser: Chrome
 - Version: Version 100.0.4896.127 (Official Build) (64-bit)
 - WSL: Version 2

**Comment by equiman** [comment]
Maybe this information can help to solve it:
https://github.com/microsoft/vscode/issues/99691

**Comment by apostolos** [comment]
If the WSL environment can be detected somehow, then the path should change to:
\\\ `{WSLHostname}` \ `{Distro}` \home\juanmartinez\DEIN\scrimba-react-vite\src\main.jsx

e.g.
`\\wsl.localhost\Ubuntu\home\juanmartinez\DEIN\scrimba-react-vite\src\main.jsx`

If that's not possible, manually setting a prop should be an acceptable workaround.

**Comment by equiman** [comment]
Yes, it can be config like the `editor="vscode-insiders"` property. Maybe something like `wsl="Ubuntu"`

**Comment by apostolos** [comment]
The following both work and open in the correct workspace:

```bash
code --file-uri vscode-remote://wsl+Ubuntu/path/to/file
code --remote wsl+Ubuntu /path/to/file.js # guesses if it's a file or folder from extension
```

However `click-to-component` needs to work with `vscode:` URLs. Unfortunately AFAICT opening in the correct `vscode-remote` 
 window is [not yet possible](https://github.com/microsoft/vscode-remote-release/issues/4779) but it's [coming soon](https://github.com/microsoft/vscode-remote-release/issues/4779#issuecomment-812780287).

**Comment by equiman** [comment]
It's true. I've tested the URI with `vscode-remote` and doesn't launch the VSCode
`vscode-remote://Ubuntu/DEIN/scrimba-react-vite/src/App.jsx:11:9`
![image](https://user-images.githubusercontent.com/933393/165599707-88331860-a04f-4b29-93aa-6e20ac032353.png)

With `vscode` ask on browser
![image](https://user-images.githubusercontent.com/933393/165601286-836ce89e-32e2-43bf-885c-a79e2db2fa7e.png)

but can't open the file on VSCode. I've tried with this combinations:
vscode://file\\wsl.localhost\Ubuntu\home\juanmartinez\DEIN\scrimba-react-vite\src\App.jsx:11:9
vscode://\\wsl.localhost\Ubuntu\home\juanmartinez\DEIN\scrimba-react-vite\src\App.jsx:11:9
vscode://file/wsl.localhost\Ubuntu\home\juanmartinez\DEIN\scrimba-react-vite\src\App.jsx:11:9
vscode://wsl.localhost/Ubuntu/home/juanmartinez/DEIN/scrimba-react-vite/src/App.jsx:11:9

**Comment by apostolos** [comment]
The following works for me, however it opens in a local vscode window instead of the correct vscode-remote workspace:

```
start vscode://file/$wsl/wsl.localhost/Ubuntu/path/to/file.jsx
```

**Comment by equiman** [comment]
I've copied the path from File Explorer
![image](https://user-images.githubusercontent.com/933393/165609786-1aed4b6d-f6c8-4e8c-841c-3323906da3fd.png)

Add put on browser address bar like this: 
`vscode://file//wsl$/Ubuntu/home/juanmartinez/DEIN/scrimba-react-vite/src/App.jsx:11:9` 

But happen me the same to you, open it another 'local' instance, instead 'wsl-remote'
![image](https://user-images.githubusercontent.com/933393/165611143-bd47a061-0dfb-4fe9-9d68-324027451538.png)

Seems to be that we are gonna need to wait until `vscode-remote://` was supported on the browser 😥

**Comment by equiman** [comment]
According to this documentation: [our-triaging-flow]( https://github.com/microsoft/vscode/wiki/Issues-Triaging#our-triaging-flow). Needs at least 20 community votes, and have 18. 

So **we need another 2 votes** more to reach it.

![map](https://user-images.githubusercontent.com/4674940/67361393-5e82d500-f51d-11e9-955a-6a14c00ba390.png)

**Comment by ericclemmons** [comment]
I've voted for https://github.com/microsoft/vscode-remote-release/issues/4779!

In the meantime, I think we're forced to close this issue **until the browser supports a `${protocol}://...` that this library can `window.open(url)` with :(

When that's ready, instead of `editor` there'll be a prop like `sourceToURL({ editor, source }): string` that you can use to craft a working URL.

**Comment by equiman** [comment]
Hi @ericclemmons, seems to be this issue finally can be solved.

```
vscode://vscode-remote/ssh-remote+[host]/[path/to/file]:[line]:[col]
```

I've tested it from the browser:

```
vscode://vscode-remote/wsl+ubuntu/home/juanmartinez/Developer/DEIN/swpm/src/swpm.js:3
```

And it will open the project using WSL on 
![image](https://user-images.githubusercontent.com/933393/186658215-24c5f94a-9a89-4944-a00a-18bc65b72051.png)

**Comment by chneau** [comment]
I've been strugling a bit to get it to work and did not achieved that but here is what I have now:

I'm using farmfe/farm (vite like), the farm react plugin can enable the locators:
![image](https://github.com/user-attachments/assets/f503855e-5b9b-40f9-b06e-4e3f29170196)

then using this extension: https://chromewebstore.google.com/detail/locatorjs/npbfdllefekhdplbkdigpncggmojpefi

you can set a custom URL.

I'm using a code ssh remote and thanks to the link earlier I ended up to this comment https://github.com/microsoft/vscode-remote-release/issues/4779#issuecomment-1220475865 helping me to tune the link properly to work for my code ssh need:

The link I use: `vscode://vscode-remote/ssh-remote+ncce/home/c/go/src/github.com/celerumltd/TLS-v4-frontend/${projectPath}${filePath}:${line}:${column}` and it works perfect
