### ISSUE TITLE
Module not found: Can't resolve 'click-to-react-component' in '/Users/mike/Documents/work/bix-b2b/src'

### ISSUE THREAD

**Issue by mylesshie** [ericclemmons/click-to-component#47]
my app was created by Create-react-app, when I use this component, I get this error;

Module not found: Can't resolve 'click-to-react-component' in '/Users/mike/Documents/work/bix-b2b/src';

<img width="481" alt="image" src="https://user-images.githubusercontent.com/4142212/170164092-751afd64-4d0b-4722-a9c6-55727ae48737.png">

React: 16.8.6
webpack: 4.x

**Comment by ericclemmons** [comment]
Are you able to reproduce with https://github.com/ericclemmons/click-to-component/tree/main/apps/cra?  It seems to be working there...
