### ISSUE TITLE
Source is undefined

### ISSUE THREAD

**Issue by deshiknaves** [ericclemmons/click-to-component#48]
**Describe the bug**
In a next js app. If you option click a component it says "Uncaught TypeError: source is undefined"

![image](https://user-images.githubusercontent.com/862834/170802865-e6b2bf68-57cb-44e0-8ee3-22a690ad78e2.png)

**To Reproduce**
1. Go to the application
2. Option click an element 

**Expected behavior**
Open the source in the editor

**Screenshots**
![image](https://user-images.githubusercontent.com/862834/170802885-12281548-78ec-4abe-b329-b57db09cb5cc.png)

**Desktop (please complete the following information):**
 - OS: Latest OSX
 - Browser Firefox
 - Version 101.0b9

**Comment by ericclemmons** [comment]
Is this happening in https://github.com/ericclemmons/click-to-component/tree/main/apps/next?  I'm not able to reproduce this.

Otherwise, see if you can modify that example to fail & open a PR so we can identify the root issue 🙏
