### ISSUE TITLE
TypeScript error "Could not find a declaration file for module"

### ISSUE THREAD

**Issue by danitatt** [ericclemmons/click-to-component#83]
**Describe the bug**
Could not find a declaration file for module 'click-to-react-component'. This error appears if tsconfig.json is set to `"strict": true`

**To Reproduce**
1. Init new project with Vite (React + typescript + SWC) `npm create vite@latest`
2. Install click-to-react-component `npm i click-to-react-component`
3. Import click-to-react-component in main.tsx
4. See typescript error

**Expected behavior**
No typescript error in VS Code.

**Screenshots**
<img width="1303" alt="Снимок экрана 2024-05-15 в 23 42 41" src="https://github.com/ericclemmons/click-to-component/assets/11528287/3b25f1f4-edf6-4fcf-a69c-78b334f7698c">

**Error from TypeScript**

> Could not find a declaration file for module 'click-to-react-component'. '/Users/danitatt/Work/nnp/app/node_modules/click-to-react-component/src/index.js' implicitly has an 'any' type. There are types at '/Users/danitatt/Work/nnp/app/node_modules/click-to-react-component/src/types.d.ts', but this result could not be resolved when respecting package.json "exports". The 'click-to-react-component' library may need to update its package.json or typings.

_Thanks for the great tool!_

**Comment by alexgorbatchev** [comment]
Seeing the same problem, could be worked around with `// @ts-expect-error` but would be nice to get this fixed :)
